Solved following problems: ActivationException: The constructor of type DbContextFactory contains the parameter with name 'namedResolvers' and type IList<KeyValuePair<string, Func<DbContextBase>>>, but IList<KeyValuePair<string, Func<DbContextBase>>> is not registered. For IList<KeyValuePair<string, Func<DbContextBase>>> to be resolved, it must be registered in the container. You can use one of the Container.Collection.Register overloads to register a collection of KeyValuePair<string, Func<DbContextBase>> types, or one of the Container.Collection.Append overloads to append a single registration to a collection. In case you intend to resolve an empty collection of KeyValuePair<string, Func<DbContextBase>> elements, make sure you register an empty collection; Simple Injector requires a call to Container.Collection.Register to be made, even in the absence of any instances. Please see https://simpleinjector.org/collections for more information about registering and resolving collections.
ActivationException: The constructor of type DbContextFactory contains the parameter with name 'singleResolver' and type Func<DbContextBase>, but Func<DbContextBase> is not registered. For Func<DbContextBase> to be resolved, it must be registered in the container.